# Generated by Django 6.0 on 2026-01-21 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image_desktop', models.ImageField(upload_to='banners/desktop/')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='banners/mobile/')),
                ('link_type', models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('collection', 'Collection'), ('external', 'External')], max_length=20)),
                ('link_value', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.bannerslot')),
            ],
        ),
    ]
