# Generated by Django 6.0 on 2026-01-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='template_type',
            field=models.CharField(blank=True, choices=[('hero_left', 'Hero Text Left'), ('hero_center', 'Hero Text Center'), ('campaign_card', 'Campaign Card'), ('category_tile', 'Category Tile'), ('strip', 'Offer Strip')], max_length=30, null=True),
        ),
    ]
