# Generated by Django 6.0 on 2026-01-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('volleyball', 'Volleyball'), ('gym', 'Gym')], max_length=20)),
                ('description', models.TextField()),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='product_images/%Y/%m/%d/')),
            ],
        ),
    ]
